### ISSUE TITLE
Error in purchasing multiple times

### ISSUE THREAD

**Issue by HardikDG** [thielCole/ionic-iap2#1]
When I click the purchase button for the 2nd or 3rd time and then I click cancel the sign in popup it is showing the alert multiple time.

It is also showing some uncaught error in the console when we click the purchase button

**Comment by captaincole** [comment]
Interesting. I'll have to take a look. Did you configure your store to connect with this implementation?

**Comment by HardikDG** [comment]
Yes. I have made changes to the store configuration. For the first time, it is loading the product details properly with an 'Uncaught error' in between.

**Comment by captaincole** [comment]
I've made some updates to the code. Could you verify you still see the issue?

**Comment by captaincole** [comment]
Gonna close this as I haven't heard much about it since.
