### ISSUE TITLE
Works but issue with initial load of Purchase

### ISSUE THREAD

**Issue by pooblej** [thielCole/ionic-iap2#7]
Hi Andrew - thanks for releasing this example.
I wanted to highlight an issue I have found during initial testing. Please can you have a look - as it makes the example hard to use / build on..

Issue is my published test app (your code but my licence and dummy product) on google play. 

1. App opens
2. User selects About
3. User selects Purchase - BUG - NOTHING HAPPENS
4. However if the user selects "Home" or "Contact" tab - on pressing it - purchase modal opens from google.
5. Once opened once - the bug does not happen - and each time user presses Purchase it works near instantly.

Attached is a zip - unzip for a mp4 showing what I mean...

Thanks again 

[bug.zip](https://github.com/thielCole/ionic-iap2/files/1663703/bug.zip)

J

**Comment by captaincole** [comment]
Interesting. Let me look through the issue and get back to you with a solution. Usually Android / Google Play is the easier of the two stores to deal with.

**Comment by francoisduchemin** [comment]
I have the same issue!
If I select another tab after having tapped "Purchase", the modal opens.
Same issue when trying to restore by the way. I have to tap "Restore" and switch to another tab in order for the restore to actually happen.

**Comment by pooblej** [comment]
I have tried various different button code in about.html
ie

SRC>Pages>About.html

---<ion-content padding>---
  ---<button ion-button (click)="purchase()">PURCHASE</button>---
---</ion-content>---

to

---<ion-content padding>---
 ---<button ion-button (tab)="purchase()">PURCHASE</button>---
---</ion-content>---

I think it improves it - but still not firing correctly.

Any one else have any ideas?

**Comment by francoisduchemin** [comment]
Not sure what you mean with PURCHASE to PURCHASE.
I am trying the other plugin available for ionic: https://ionicframework.com/docs/native/in-app-purchase/

**Comment by captaincole** [comment]
I have seen issues here related to async await not running inside the correct zone in angular. Thats my first angle of attack. Angular runs change detection on page transition, but potentially not on button click.

**Comment by captaincole** [comment]
Hey guys, found the problem. It was an issue of configuring the purchase before making it.

**Comment by francoisduchemin** [comment]
Cool thanks! Btw you committed your billing key in package.json
You may want to remove it.

**Comment by captaincole** [comment]
@francoisduchemin Good catch 💯 Guess I need to go change my own billing key
